server.port=8081
spring.application.name=company-management

spring.datasource.url=jdbc:postgresql://ep-cold-tooth-aq9uvrww.c-8.us-east-1.aws.neon.tech:5432/neondb?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory

spring.datasource.username=neondb_owner
spring.datasource.password=npg_FXR3VDxz0cqy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.connection-timeout=30000

# ========== Mail Configuration ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sms.system.noreply@gmail.com
spring.mail.password=phprbegknmxrbnga
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# ========== JWT Configuration ==========
app.jwt.secret=ccf94852c95026fd19bb28889ee3517c1ffe7b55d904541a3aa0b022315c65f6
app.jwt.access-token-expiration=3600000
app.jwt.refresh-token-expiration=604800000

# ========== Authentication Configuration ==========
app.auth.max-failed-attempts=5
app.auth.lock-duration-minutes=15
